### PR TITLE
Migrate from createClass() to es6 classes

### LINKED ISSUE #68: React v15.5 createClass() deprecation
React v15.5 is removing createClass() in favor of native es6 classes, is there any opposition to a PR to update react-bootstrap-multiselect to use es6 classes?

### PR DESCRIPTION
**Pull request by sman591**
Fixes #68 

Also had to add babel to the gulp build in order to properly build the demo app.

The demo app & readme also could use some updating, but I figure that can happen outside of this PR.

I've tested this with the demo app & my own app (though had to fix a bootstrap import on a [custom branch](https://github.com/sman591/react-bootstrap-multiselect/tree/fix-bootstrap)).

### CODE REVIEW

**Comment by skratchdot** [comment]
Thanks for this! I've been wanting to update the demo, or use react-storybook instead.  I'd also like to make sure builds work with webpack (since that's what most people, including me, are using nowadays).  I'll pull this in and push a new build.

**Comment by skratchdot** [comment]
I also don't like the "Note on data synchronization" that I merged in at one point.  I'd like to update that for people b/c it doesn't look like any other typical React usage I've seen....

**Comment by sman591** [comment]
Happy to!

**Comment by skratchdot** [comment]
@sman591 - I just published 2.4.0 with your changes. Thanks again!

**Pull request merged**
