### PR TITLE
a bug that led the menu can not display

### PR DESCRIPTION
**Pull request by songquanwang**
Dear:
     I use this lib in my project , but its really suprised me that  the drop menus can't display. So I debug and find the problom. I don't confirm if this is a bug or not.

### CODE REVIEW

**Comment by skratchdot** [comment]
Hi. Thanks for the pull request. The file you changed is pulled automatically from the upstream library here: https://github.com/davidstutz/bootstrap-multiselect

So if you want this change to be made, you'll need to submit a pull request there.  Thanks again.

**Comment by netsgnut** [comment]
I have faced a similar problem that Dropdown could not initialize itself - while changing the line as @songquanwang said seems to solve the problem, I doubt if it is the right cure.

Not sure if this is the right place to chime in but here it is.

What I have here is a Bootstrap 3.3.5 project with Webpack enabled. I have included the `react-bootstrap-multiselect` library there alongside with the common Bootstrap libraries. However I observe that it no longer works - been using `bootstrap-multiselect` and is trying to migrate some part of legacy codes to use React, but `react-bootstrap-multiselect` buttons do not toggle itself.

However once I replace `lib/bootstrap-dropdown.js` with an empty stub, i.e.
```js
exports.init = function (jQuery) { return jQuery; };
```
...it starts working again. Alternatively I can stop packing the `bootstrap-dropdown` from Bootstrap libraries and it works too.

Can @songquanwang also confirm if that works for you too? Thanks.

**Comment by skratchdot** [comment]
@netsgnut - Weird- I made the same change and it seemed to work, but then I updated all my libs, and re-built the demo site, and it didn't seem to work until I re-added the bootstrap-dropdown.js file again.  Anyways, the newly published version is using bootstrap 3.5, and it *seems* to work for me right now.

I'd like to figure out how to get this lib to work correctly with browserify/webpack without needed the weird `require('jquery')` and `require('bootstrap-dropdown')` logic I added.

**Comment by netsgnut** [comment]
@skratchdot I think I should have found a lead down the rabbit hole.

Investigating my build here there are two `jquery` imported. The reason is that my project has specified `jquery` to be in `1.11.3` ([like the Bootstrap 3.3.5 upstream](https://github.com/twbs/bootstrap/tree/v3.3.5/js/tests/vendor)), however since our library here tries to load a `^2.1.4` version of `jquery`, what `webpack` does is it injects the dropdown logic into a newer version of the library.

Typically it shouldn't cause much trouble as it has some sort of [`noConflict` mechanism](https://github.com/skratchdot/react-bootstrap-multiselect/blob/v0.3.0/lib/bootstrap-dropdown.js#L141-L153) that does the renaming under the hood. However things get really go nasty when both libraries, *from different jQuery version*, to [manipulate the document DOM *together*](https://github.com/skratchdot/react-bootstrap-multiselect/blob/v0.3.0/lib/bootstrap-dropdown.js#L156-L164). I dare not going down digging through the case of two simultaneous jQuery builds, each with different feature set, loading together - but I kinda empirically verify that by removing either one of the builds' `$(document).doWhatever()` block it would work.

As a workaround on my [testing branch](https://github.com/netsgnut/react-bootstrap-multiselect/tree/master) I did two things:
1. Changed `package.json` so that it allows jQuery 1 as well [(diff)](https://github.com/netsgnut/react-bootstrap-multiselect/commit/af09745e5b5601c8e0a78766a57d25d8029aae95)
2. Added a guard against double-loading of Bootstrap Dropdown plugin [(diff)](https://github.com/netsgnut/react-bootstrap-multiselect/commit/dc736c2f6c535f33b2be3baf392f04eb41754290)

I am making a new PR for this feature. Please see if we should publish yet another new version to deal with that ;)

IMHO, it might be a good idea to link the upstream libraries in `package.json` instead of including them raw in the source code so that Webpack knows how to package the file better. However seeing that you have to wrap the upstream libraries manually with a `module.exports` it may be much more tricky then it actually sounds if we are to do it right now for Bootstrap 3... [On the brighter side things do look a lot better in Bootstrap 4 though with ES6 exports](https://github.com/twbs/bootstrap/blob/v4.0.0-alpha/js/src/dropdown.js).

**Comment by songquanwang** [comment]
@netsgnut  I think  the lib/bootstrap-dropdown is same funtion with the up-stream bootstrap-dropdown ,just you said ". Alternatively I can stop packing the bootstrap-dropdown from Bootstrap libraries ",I try it and  it really so.

**Comment by netsgnut** [comment]
@songquanwang Thanks! Would you mind trying my testing branch as well? In that case, please try to package the `bootstrap-dropdown` just like before, but this time use my branch instead of the official branch.

FYI you can use my branch by replacing the `"react-bootstrap-multiselect": "0.2.2"` line to be `"react-bootstrap-multiselect": "netsgnut/react-bootstrap-multiselect#dropdown-conflict-fix"` and do a `npm install`.

**Pull request closed without merging**
