### PR TITLE
Allow the module to be used in Universal apps

### PR DESCRIPTION
**Pull request by angelaigreja**
jquery can not be initialised with nodeJs since there is no window or document.

### CODE REVIEW

**Comment by ananddodia** [comment]
Still i am getting below mention error
ReferenceError: window is not defined
[1]     at Object.<anonymous> (../node_modules/react-bootstrap-multiselect/dist/index.js:18:2)

Can you please fix it? or help me with a solution.
the issue is in this code.
if (typeof window !== 'undefined' && window && window.jQuery) {
	$ = window.jQuery;
} else {
	$ = require('jquery');
	window.jQuery = $;
}

when we are already checking for 'window' object in if condition. We cannot use that in else clause.

**Comment by sman591** [comment]
Ah, that's my mistake - I added window.jQuery in the else not fully realizing it's original purpose. I'll submit a PR to fix.

**Comment by sman591** [comment]
PR opened: #75

**Comment by ananddodia** [comment]
thanks @sman591 for replying in short time.
After applying your patch. Now i am getting error in node_modules/bootstrap/js/transition.js:59:3
error is ReferenceError: jQuery is not defined
at Object.<anonymous> (/var/www/.../node_modules/bootstrap/js/transition.js:59:3)
I tried to debug and found that in jQuery object is not found. Can you please help?

**Comment by sman591** [comment]
@ananddodia Looks like that might be due to changes #61 that introduced importing the boostrap package directly. This was reported in #73 - I posted [a temporary workaround](https://github.com/skratchdot/react-bootstrap-multiselect/issues/73#issuecomment-296724952) as well.

**Pull request merged**
